version: '3'
services:

  kafka:
    container_name: app-kafka
    image: wurstmeister/kafka
    ports:
      - 9092:9092
      - 1099:1099
    environment:
      JMX_PORT: 1099
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_JMX_OPTS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.port=1099 -Dcom.sun.management.jmxremote.rmi.port=1099 -Djava.rmi.server.hostname=kafka"
    labels:
      com.datadoghq.ad.check_names: '["kafka"]'
      com.datadoghq.ad.init_configs: '[{"is_jmx": true, "collect_default_metrics": true}]'
      com.datadoghq.ad.instances: '[{"host": "%%host%%", "port": 1099}]'
      com.datadoghq.ad.logs: '[{"source": "kafka", "service": "app-kafka"}]'
      com.datadoghq.tags.env: 'prod'
      com.datadoghq.tags.service: 'app-kafka'
      com.datadoghq.tags.version: '1.0'

  zookeeper:
    container_name: app-zookeeper
    image: wurstmeister/zookeeper
    labels:
      com.datadoghq.ad.check_names: '["zk"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: '[{"host": "%%host%%", "port": "2181"}]'
      com.datadoghq.ad.logs: '[{"source": "zookeeper", "service": "app-kafka"}]'
      com.datadoghq.tags.env: 'prod'
      com.datadoghq.tags.service: 'app-kafka'
      com.datadoghq.tags.version: '1.0'

# This network matches the network name where the Datadog agent is running
networks:
  default:
    external:
      name: network-apm