version: '3.8'
services:

  # PG Admin Tool for PostgreSQL
  pgadmin:
    image: dpage/pgadmin4
    container_name: intg-confluence-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=<your-email@email.com>
      - PGADMIN_DEFAULT_PASSWORD=datadog
    ports:
      - 5050:80
    volumes:
      - pgadminData:/pgadmin4
      - pgAdminApplicationData:/var/lib/pgadmin

networks:
  default:
    external:
      name: network-apm

volumes:
  pgadminData:
  pgAdminApplicationData: