apiVersion: v1
kind: Service
metadata:
  name: app-flask-service
spec:
  selector:
    app: app-flask
  ports:
  - protocol: "TCP"
    port: 5000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-flask
  labels:
    tags.datadoghq.com/env: "k8s"
    tags.datadoghq.com/service: "app-flask"
    tags.datadoghq.com/version: "1.0.0"
spec:
  selector:
    matchLabels:
      app: app-flask
  replicas: 4
  template:
    metadata:
      labels:
        app: app-flask
        tags.datadoghq.com/env: "k8s"
        tags.datadoghq.com/service: "app-flask"
        tags.datadoghq.com/version: "1.0.0"
    spec:
      containers:
        - name: app-flask
          image: app-flask:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
            - name: DD_TRACE_ANALYTICS_ENABLED
              value: "true"
            - name: DD_RUNTIME_METRICS_ENABLED
              value: "true"
            - name: DD_PROFILING_ENABLED
              value: "true"
            - name: DD_LOGS_INJECTION
              value: "true"
            - name: DD_TRACE_AGENT_PORT
              value: "8126"
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_ENV
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/env']
            - name: DD_SERVICE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/service']
            - name: DD_VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/version']