version: '3'

services:

  db:
    container_name: app-wordpress-db
    build: ./services/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=datadog
      - MYSQL_USER=wordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_PASSWORD=wordpress
    labels:
      com.datadoghq.ad.check_names: '["mysql"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: >-
        [ {
          "host": "%%host%%",
          "port":3306,
          "user":"datadog",
          "pass":"datadog",
          "options": {
            "replication": "false",
            "extra_status_metrics": "true",
            "extra_innodb_metrics": "true",
            "extra_performance_metrics": "true",
            "schema_size_metrics": "false",
            "disable_innodb_metrics": "false"
          }
        } ]
      com.datadoghq.ad.logs: '[{"source": "mysql", "service": "mysql"}]'
      com.datadoghq.tags.env: 'prod'
      com.datadoghq.tags.service: 'app-wordpress'
      com.datadoghq.tags.version: '1.0'

  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile
    container_name: app-wordpress-web
    ports:
      - 8091:80
    restart: always
    env_file:
      - .env.prod
    volumes:
      - app:/var/www/html
    labels:
      com.datadoghq.ad.check_names: '["apache"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: '[{"apache_status_url": "http://%%host%%/server-status?auto"}]'
      com.datadoghq.ad.logs: '[{"source": "apache", "service": "app-wordpress"}]'
      com.datadoghq.tags.env: 'prod'
      com.datadoghq.tags.service: 'app-wordpress'
      com.datadoghq.tags.version: '1.0'

  # adminer:
  #   build:
  #     context: ./services/adminer
  #     dockerfile: Dockerfile
  #   container_name: app-wordpress-adminer
  #   environment:
  #     ADMINER_DEFAULT_SERVER: db
  #   ports:
  #     - 8099:8080

networks:
  default:
    external:
      name: network-apm

volumes:
    app:
    db_data:



