version: '3.8'
services:

    db:
      container_name: app-rails-db
      build:
        context: ./services/postgresql
        dockerfile: Dockerfile
      volumes:
        - ./tmp/db:/var/lib/postgresql/data
      environment:
        POSTGRES_PASSWORD: password

    web:
      container_name: app-rails-web
      build: .
      command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
      volumes:
        - .:/myapp
      ports:
        - "3000:3000"
      depends_on:
        - db
      environment:
          - DD_AGENT_HOST=datadog-agent
          - DD_AGENT_PORT=8126
          - DD_ENV=prod
          - DD_SERVICE=app-rails
          - DD_VERSION=1.0
networks:
  default:
    external:
      name: network-apm