version: '3'

services:

  db:
    container_name: app-django-db
    build: ./services/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_PASS=datadog
      - MYSQL_ROOT_PASSWORD=datadog
      - MYSQL_USER=datadog
    labels:
      com.datadoghq.ad.check_names: '["mysql"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: '[{"host":"%%host%%", "port":3306, "user":"datadog", "pass":"datadog"}]'
      com.datadoghq.ad.logs: '[{"source": "mysql", "service": "mysql"}]'
      com.datadoghq.tags.env: 'prod'
      com.datadoghq.tags.service: 'app-django'
      com.datadoghq.tags.version: '1.0'

  web:
    container_name: app-django-web
    build:
      context: ./services/web
      dockerfile: Dockerfile.prod
    command: ddtrace-run python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./services/web/app:/usr/src/app
    expose:
      - 8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
    labels:
      com.datadoghq.ad.check_names: '["gunicorn"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: '[{"proc_name": "app-django"}]'
      com.datadoghq.ad.logs: '[{"source": "python", "service": "app-django", "sourcecategory": "sourcecode"}]'
      com.datadoghq.tags.env: 'prod'
      com.datadoghq.tags.service: 'app-django'
      com.datadoghq.tags.version: '1.0'

volumes:
  static_volume: