source 'https://rubygems.org'

gem 'sinatra', '~> 2.0', '>= 2.0.8.1'
gem 'sinatra-contrib', '~> 2.0', '>= 2.0.8.1'

# Datadog Tracing
gem 'ddtrace'

group :development do
  gem 'ruby-debug-ide', '~> 0.7.0'
end
